version: '3'
services:
  app:
    build: .
    command: node server.js
    ports:
      - "3000:3000" # Map the app's port to a port on the host (if required)
    env_file:
      - .env.docker  # Load the .env file

  # ws:
  #   build: .
  #   command: npm run ws
  #   ports:
  #     - "8080:8080" # Map the WebSocket server port to the host
  #   env_file:
  #     - .env  # Load the .env file

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "3030:3030" # Map Redis port to the host (if your Redis server is on port 3030)
  #   env_file:
  #     - .env  # Load the .env file
